security:
    firewalls:
        extranet:
            pattern: ^/extranet
            provider: tiendas
            anonymous: ~
            form_login:
                login_path: /extranet/login/
                check_path: /extranet/login_check/
            logout:
                path: /extranet/logout/
                target: /extranet/

        frontend:
            pattern: ^/*
            provider: usuarios
            anonymous: ~
            form_login:
                login_path: /usuario/login/
                check_path: /usuario/login_check/
            logout:
                path: /usuario/logout/

    access_control:
        - { path: ^/(es|en)/usuario/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(es|en)/usuario/registro, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(es|en)/usuario/*, roles: ROLE_USUARIO }
        - { path: ^/extranet/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/extranet/*, roles: ROLE_TIENDA }

    providers:
        usuarios:
            entity: { class: AppBundle:Usuario, property: email }

        tiendas:
            entity: { class: AppBundle:Tienda, property: login}

    encoders:
#        AppBundle\Entity\Usuario: { algorithm: sha512, iterations: 10 }
        AppBundle\Entity\Usuario:
            algorithm: bcrypt
            iterations: 10
        AppBundle\Entity\Tienda:
            algorithm: bcrypt
            iterations: 10

    access_decision_manager:
        strategy: unanimous