security:
    firewalls:
        frontend:
            pattern:     ^/*
            anonymous:   ~
            form_login:
                login_path: /usuario/login/
                check_path: /usuario/login_check/
            logout:
                path: /usuario/logout/

    access_control:
        - { path: ^/(es|en)/usuario/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(es|en)/usuario/registro, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(es|en)/usuario/*, roles: ROLE_USUARIO }

    providers:
        usuarios:
            entity: { class: AppBundle:Usuario, property: email }

    encoders:
#        AppBundle\Entity\Usuario: { algorithm: sha512, iterations: 10 }
        AppBundle\Entity\Usuario: bcrypt
        AppBundle\Entity\Tienda: bcrypt
