# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

    twig.extension.cupon:
        class: AppBundle\Twig\AppExtension
        tags:
            - { name: twig.extension }

    login_listener:
        class: AppBundle\EventListener\LoginListener
        arguments: ['@router']
        tags:
            - { name: kernel.event_listener, event: security.interactive_login }
            - { name: kernel.event_listener, event: kernel.response }

    listener_request:
        class: AppBundle\EventListener\RequestListener
        tags:
            - { name: kernel.event_listener, event: kernel.request}

    intl.twig.extension:
        class: Twig_Extensions_Extension_Intl
        tags: [{ name: 'twig.extension'}]